"""Declarative hookset models, compilation, validation, and installation."""

from .check import CheckReport, check_hookset
from .collection import (
    CollectionCheckReport,
    CollectionMember,
    check_collection,
    combine_configs,
    compile_collection,
    resolve_collection,
    selected_providers,
)
from .compiler import (
    CompiledConfig,
    ProviderSelection,
    compile_hookset,
    compile_hooksets,
    resolve_app_spec,
    target_providers,
)
from .install import (
    ConfigChange,
    Scope,
    config_dict,
    default_config_path,
    install_collection_config,
    install_config,
    merge_managed_collection_config,
    merge_managed_config,
    read_json_object,
    uninstall_collection_config,
    uninstall_config,
)
from .launcher import default_command_prefix, self_install_spec
from .models import (
    ClaudeCodeHookSet,
    ClaudeCodeHookSpec,
    CodexHookSet,
    CodexHookSpec,
    FastmcpHookSet,
    FastmcpHookSpec,
    HookCollection,
    HookSet,
    HookTarget,
    ProviderName,
    SharedHookSet,
    SharedHookSpec,
    parse_hook_collection,
    parse_hook_target,
    parse_hookset,
    read_hook_collection,
    read_hook_target,
    read_hookset,
)

__all__ = [
    "CheckReport",
    "CollectionCheckReport",
    "CollectionMember",
    "ClaudeCodeHookSet",
    "ClaudeCodeHookSpec",
    "CodexHookSet",
    "CodexHookSpec",
    "CompiledConfig",
    "ConfigChange",
    "FastmcpHookSet",
    "FastmcpHookSpec",
    "HookSet",
    "HookCollection",
    "HookTarget",
    "ProviderName",
    "ProviderSelection",
    "Scope",
    "SharedHookSet",
    "SharedHookSpec",
    "check_collection",
    "check_hookset",
    "combine_configs",
    "compile_collection",
    "compile_hookset",
    "compile_hooksets",
    "config_dict",
    "default_config_path",
    "default_command_prefix",
    "install_collection_config",
    "install_config",
    "merge_managed_collection_config",
    "merge_managed_config",
    "parse_hook_collection",
    "parse_hook_target",
    "parse_hookset",
    "read_hook_collection",
    "read_hook_target",
    "read_hookset",
    "read_json_object",
    "resolve_collection",
    "resolve_app_spec",
    "selected_providers",
    "self_install_spec",
    "target_providers",
    "uninstall_collection_config",
    "uninstall_config",
]
